
config = {
    "use_layoutLM": True,
    "use_gemini": True,
    "use_regex": True,
    "gemini_config": {
        "model_list": ["gemini-3-flash-preview", "gemini-2.5-flash", "gemini-3-flash-lite-preview", "gemini-2.5-flash-lite"],
        "temperature": 0, # temperature: Controls randomness in generation (lower = more deterministic, higher = more creative)
        "top_p": 0.1, # top_p: Limits token selection to the smallest probability mass whose cumulative probability exceeds p
        "top_k": 1, # top_k: Restricts next-token selection to the top K most probable tokens
        "candidate_count": 1, # candidate_count: Number of complete response variations generated by the model
        "max_output_tokens": 256,

        "max_attempts_per_model": 3,
        "delay_between_consecutive_queries": 3, # in seconds
    },
    "max_workers": 4, # adjust to find correct tradeoff between memory usage and speed, if should not be more than total CPU cores
}




